version: 2.1
 
orbs:
  android: circleci/android@0.2.1
 
jobs:
  build:
    executor:
      name: android/android
      resource_class: medium
      environment:
      JDK_URL: "https://download.java.net/java/GA/jdk17/0d1cfde4252546c6931946de8db48ee2/35/GPL/openjdk-17_linux-x64_bin.tar.gz"
    steps:
      - checkout
      - run:
          name: Install JDK 17
          command: |
            curl -O $JDK_URL
            sudo tar xzvf openjdk-17_linux-x64_bin.tar.gz -C /usr/local
            sudo update-alternatives --install /usr/bin/java java /usr/local/jdk-17/bin/java 1
            sudo update-alternatives --set java /usr/local/jdk-17/bin/java
            java -version
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
